extends Node

var FOOD = "FOOD"
var CLOTHES = "CLOTHES"
var IRON_ORE = "IRON_ORE"
var BUILDING_MATERIALS = "BUILDING_MATERIALS"



enum PRODUCTION_TYPE {NONE, MANUAL_LABOR, AGRICULTURE}

enum HAULING_TYPE {NONE, COLLECT_ALL_TO}
